In [1]:
from pathlib import Path
import pandas as pd

In [2]:
# project root
BASE_DIR = Path().resolve().parent

DATA_PATH = BASE_DIR / "ukraine-attacks-analysis" / "data" / "raw" / "missile_attacks_daily.csv"

print(DATA_PATH)
print(DATA_PATH.exists())

/Users/vitalii/Documents/ukraine-attacks-analysis/data/raw/missile_attacks_daily.csv
True

In [3]:
df = pd.read_csv(DATA_PATH)

df.head()

,time_start,time_end,model,launch_place,target,target_main,launched,destroyed,not_reach_goal,still_attacking,...,num_hit_location,num_fall_fragment_location,carrier,turbojet,turbojet_destroyed,affected region,destroyed_details,launched_details,launch_place_details,source
0,2026-04-18 17:30,2026-04-19 08:00,Shahed-136/131,Primorsko-Akhtarsk and Kursk oblast and Bryans...,Ukraine,NaN,236.0,203.0,0.0,1.0,...,18.0,8.0,NaN,NaN,NaN,NaN,"{'south': 23, 'east': NaN, 'north': NaN}",NaN,NaN,kpszsu/posts/pfbid0MeNK3NXQXEE3UZmCEd9ACbScZTX...
1,2026-04-17 18:00,2026-04-18 08:30,Shahed-136/131,"Primorsko-Akhtarsk and Chauda, Crimea and Kurs...",Ukraine,NaN,219.0,190.0,0.0,1.0,...,17.0,9.0,NaN,NaN,NaN,NaN,"{'south': 56, 'east': NaN, 'north': NaN}",NaN,NaN,kpszsu/posts/pfbid02SbNVam4xqrQuM1pWKBGqKsMprJ...
2,2026-04-18,2026-04-18,Unknown UAV,NaN,south,NaN,62.0,62.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PvKPivden/posts/pfbid02QHv7o6nNNq7wsjui4ixPYDG...
3,2026-04-16 18:00,2026-04-17 08:00,Shahed-136/131,Primorsko-Akhtarsk and Kursk oblast and Bryans...,Ukraine,NaN,172.0,147.0,0.0,5.0,...,8.0,4.0,NaN,NaN,NaN,NaN,"{'south': 86, 'east': NaN, 'north': NaN}",NaN,NaN,kpszsu/posts/pfbid0fWmfYz3KEHzAskn2FhyBgruZ2wR...
4,2026-04-16 18:00,2026-04-17 08:00,Iskander-M,Crimea,Ukraine,NaN,1.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kpszsu/posts/pfbid0fWmfYz3KEHzAskn2FhyBgruZ2wR...

In [4]:
df.shape

(3617, 22)

In [5]:
df.columns

Index(['time_start', 'time_end', 'model', 'launch_place', 'target',
       'target_main', 'launched', 'destroyed', 'not_reach_goal',
       'still_attacking', 'border_crossing', 'is_shahed', 'num_hit_location',
       'num_fall_fragment_location', 'carrier', 'turbojet',
       'turbojet_destroyed', 'affected region', 'destroyed_details',
       'launched_details', 'launch_place_details', 'source'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3617 entries, 0 to 3616
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   time_start                  3617 non-null   object
 1   time_end                    3617 non-null   object
 2   model                       3617 non-null   object
 3   launch_place                1871 non-null   object
 4   target                      3587 non-null   object
 5   target_main                 57 non-null     object
 6   launched                    3614 non-null   float64
 7   destroyed                   3611 non-null   float64
 8   not_reach_goal              642 non-null    float64
 9   still_attacking             159 non-null    float64
 10  border_crossing             3617 non-null   object
 11  is_shahed                   223 non-null    float64
 12  num_hit_location            331 non-null    float64
 13  num_fall_fragment_location  314 non-null    float64
 14  carrier                     305 non-null    object
 15  turbojet                    3 non-null      float64
 16  turbojet_destroyed          3 non-null      float64
 17  affected region             212 non-null    object
 18  destroyed_details           792 non-null    object
 19  launched_details            6 non-null      object
 20  launch_place_details        7 non-null      object
 21  source                      3617 non-null   object
dtypes: float64(9), object(13)
memory usage: 621.8+ KB

In [7]:
df.head(10)

,time_start,time_end,model,launch_place,target,target_main,launched,destroyed,not_reach_goal,still_attacking,...,num_hit_location,num_fall_fragment_location,carrier,turbojet,turbojet_destroyed,affected region,destroyed_details,launched_details,launch_place_details,source
0,2026-04-18 17:30,2026-04-19 08:00,Shahed-136/131,Primorsko-Akhtarsk and Kursk oblast and Bryans...,Ukraine,NaN,236.0,203.0,0.0,1.0,...,18.0,8.0,NaN,NaN,NaN,NaN,"{'south': 23, 'east': NaN, 'north': NaN}",NaN,NaN,kpszsu/posts/pfbid0MeNK3NXQXEE3UZmCEd9ACbScZTX...
1,2026-04-17 18:00,2026-04-18 08:30,Shahed-136/131,"Primorsko-Akhtarsk and Chauda, Crimea and Kurs...",Ukraine,NaN,219.0,190.0,0.0,1.0,...,17.0,9.0,NaN,NaN,NaN,NaN,"{'south': 56, 'east': NaN, 'north': NaN}",NaN,NaN,kpszsu/posts/pfbid02SbNVam4xqrQuM1pWKBGqKsMprJ...
2,2026-04-18,2026-04-18,Unknown UAV,NaN,south,NaN,62.0,62.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PvKPivden/posts/pfbid02QHv7o6nNNq7wsjui4ixPYDG...
3,2026-04-16 18:00,2026-04-17 08:00,Shahed-136/131,Primorsko-Akhtarsk and Kursk oblast and Bryans...,Ukraine,NaN,172.0,147.0,0.0,5.0,...,8.0,4.0,NaN,NaN,NaN,NaN,"{'south': 86, 'east': NaN, 'north': NaN}",NaN,NaN,kpszsu/posts/pfbid0fWmfYz3KEHzAskn2FhyBgruZ2wR...
4,2026-04-16 18:00,2026-04-17 08:00,Iskander-M,Crimea,Ukraine,NaN,1.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kpszsu/posts/pfbid0fWmfYz3KEHzAskn2FhyBgruZ2wR...
5,2026-04-17,2026-04-17,Unknown UAV,NaN,south,NaN,77.0,77.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PvKPivden/posts/pfbid02hYwGakgbp1kdhaZh7cW4ofR...
6,2026-04-15 07:00,2026-04-16 07:00,X-101/X-555,Caspian Sea,Ukraine,NaN,20.0,19.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kpszsu/posts/pfbid023LBuYXo2616XME3NmgDCD5kHF1...
7,2026-04-15 07:00,2026-04-16 07:00,Shahed-136/131,Primorsko-Akhtarsk and Kursk oblast and Bryans...,Ukraine,NaN,659.0,636.0,0.0,3.0,...,26.0,25.0,NaN,NaN,NaN,NaN,"{'south': 201, 'east': NaN, 'north': NaN}",NaN,NaN,kpszsu/posts/pfbid023LBuYXo2616XME3NmgDCD5kHF1...
8,2026-04-15 07:00,2026-04-16 07:00,Iskander-K,NaN,Ukraine,NaN,5.0,4.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kpszsu/posts/pfbid023LBuYXo2616XME3NmgDCD5kHF1...
9,2026-04-15 07:00,2026-04-16 07:00,C-400 and Iskander-M,NaN,Ukraine,NaN,19.0,8.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,{'south': 4},NaN,NaN,kpszsu/posts/pfbid023LBuYXo2616XME3NmgDCD5kHF1...

In [8]:
df.describe()

,launched,destroyed,not_reach_goal,still_attacking,is_shahed,num_hit_location,num_fall_fragment_location,turbojet,turbojet_destroyed
count,3614.000000,3611.000000,642.000000,159.000000,223.000000,331.000000,314.000000,3.000000,3.000000
mean,28.526287,21.016893,20.331776,3.245283,106.448430,11.039275,4.369427,7.333333,7.000000
std,71.151719,57.298156,37.367391,4.975531,77.577313,5.634980,6.180239,3.055050,3.605551
min,1.000000,0.000000,0.000000,0.000000,10.000000,0.000000,0.000000,4.000000,3.000000
25%,1.000000,1.000000,0.000000,1.000000,60.000000,7.000000,0.000000,6.000000,5.500000
50%,3.000000,2.000000,2.500000,2.000000,80.000000,10.000000,2.000000,8.000000,8.000000
75%,18.000000,14.000000,30.000000,4.000000,110.000000,14.000000,6.000000,9.000000,9.000000
max,810.000000,747.000000,415.000000,46.000000,400.000000,34.000000,44.000000,10.000000,10.000000

In [17]:
# Create attack type classification based on model and is_shahed columns

def classify_attack(row):
    model = str(row['model']).lower()
    
    if 'shahed' in model or row.get('is_shahed', 0) == 1:
        return 'drone'
    elif any(x in model for x in ['iskander', 'kalibr', 'kh-', 'x-', 'kinzhal']):
        return 'missile'
    elif 'uav' in model:
        return 'drone'
    else:
        return 'other'

df['attack_type'] = df.apply(classify_attack, axis=1)

In [18]:
# Create Clean Data

df['attack_type'] = df['attack_type'].astype(str)
df['date'] = pd.to_datetime(df['time_start'], errors='coerce').dt.date

In [19]:
df.applymap(type).head()

/var/folders/p0/h3y7y30n1b5blkgn9hvfmr5h0000gn/T/ipykernel_1300/3477424637.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(type).head()

,time_start,time_end,model,launch_place,target,target_main,launched,destroyed,not_reach_goal,still_attacking,...,carrier,turbojet,turbojet_destroyed,affected region,destroyed_details,launched_details,launch_place_details,source,attack_type,date
0,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,...,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'str'>,<class 'float'>,<class 'float'>,<class 'str'>,<class 'str'>,<class 'datetime.date'>
1,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,...,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'str'>,<class 'float'>,<class 'float'>,<class 'str'>,<class 'str'>,<class 'datetime.date'>
2,<class 'str'>,<class 'str'>,<class 'str'>,<class 'float'>,<class 'str'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,...,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'str'>,<class 'str'>,<class 'pandas._libs.tslibs.nattype.NaTType'>
3,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,...,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'str'>,<class 'float'>,<class 'float'>,<class 'str'>,<class 'str'>,<class 'datetime.date'>
4,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,...,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'str'>,<class 'str'>,<class 'datetime.date'>

In [20]:
daily = (
    df.groupby(['date', 'attack_type'])['launched']
    .sum()
    .reset_index()
)

In [21]:
daily_pivot = daily.pivot(index='date', columns='attack_type', values='launched').fillna(0)

In [23]:
df['attack_type'].value_counts()

attack_type
drone      1469
missile    1090
other      1058
Name: count, dtype: int64

In [24]:
daily_pivot.head()

attack_type  drone  missile  other
date
2022-09-29     7.0      0.0    0.0
2022-10-01     0.0      0.0    1.0
2022-10-02     7.0      0.0    0.0
2022-10-05     1.0      0.0    1.0
2022-10-06     5.0      0.0    3.0